// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCVbEIkYfNtfehITIBkfyGX8q9e314YQ8',
    appId: '1:569655433976:web:5339d738a33b147651f90d',
    messagingSenderId: '569655433976',
    projectId: 'ecommerce-app-bc5bf',
    authDomain: 'ecommerce-app-bc5bf.firebaseapp.com',
    storageBucket: 'ecommerce-app-bc5bf.appspot.com',
    measurementId: 'G-KGPT5QQX6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUxjMfXs0qfDrcJaI6HVe2NP43zZxSF7s',
    appId: '1:569655433976:android:7edc4171a9b71f0f51f90d',
    messagingSenderId: '569655433976',
    projectId: 'ecommerce-app-bc5bf',
    storageBucket: 'ecommerce-app-bc5bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR9bPdPs4JzRpWpWTo2WK9x41Rk4GU7v8',
    appId: '1:569655433976:ios:b62ef9dde9bd56a651f90d',
    messagingSenderId: '569655433976',
    projectId: 'ecommerce-app-bc5bf',
    storageBucket: 'ecommerce-app-bc5bf.appspot.com',
    iosBundleId: 'com.example.bazar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR9bPdPs4JzRpWpWTo2WK9x41Rk4GU7v8',
    appId: '1:569655433976:ios:e6e35cf039e6594251f90d',
    messagingSenderId: '569655433976',
    projectId: 'ecommerce-app-bc5bf',
    storageBucket: 'ecommerce-app-bc5bf.appspot.com',
    iosBundleId: 'com.example.bazar.RunnerTests',
  );
}
